sudo: required
language: go

dist: bionic

go:
- "1.13"

script:
- docker buildx version
- make docker || travis_terminate 1;
- make dist

before_script:
  - ./hack/upgrade-docker.sh
  - ./hack/install-buildx.sh

after_success:
  - make docker-login
  - make push

before_deploy:
  - ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
    secure: ScyGVEd7MSfjz7edf2hRDulei4ot7bTqBOJlzJMbuwdXaDKvVXXUGGwQN2PwdIDyTz5ziuqRXZjQ7ufo3KG/5c9NraZUBSGBudW1hZWjF/xRkGnkWiKGZpy+b961dE6MMSzkOz4ZmFJuvqDdV0ALzy8FCBFoacj3+n5cVcV7H7iZfvxXP4Bf4ryVxnGUaUqalmorjCeSL08UQu+Zb0vvctSxfcnUlMVCfIfa0YKgWq5/qgoNsXFg2FektDyLM7FvOUQipOKkm78HP5uQiv+eS+2kdlvd+7F8S7VSnP91qyeHQypeg6T0mswxIz7lCmtWEDcYfBAQb4BZg/T3v6U4uecust14vYMNCdkT6RgpySnIjJfcH+lYsSUvOJJJWDTHPkNXM3K94IQGxYeGcbat4aeEEtwfo7ICG22LOBKRKuo/KwQpuPZoy9cUM8Aa3Muq2yyrCZ5KFlLBMKOJOkAe2IILNaCyxa2izexpUvd75/1B1yIYlcoquVYyzawuVyIDibWCxV6QEhA2T9oJooPh1kjgKyrmbfeq5gcHpfbUKwoyNyGScrHzqfrcEATD8AYtJQRxBSj2j2mB8B2IjeHcLXu1tYnVl8Ortp5WXP0XAN7lC8ziwGlJQPN+yEJ1LGkvqrq+cwKYoBm19X4crx02Ljql1rOPz8hixcRAs6r3WUk=
  file:
  - bin/license-check
  - bin/license-check.sha256
  - bin/license-check-darwin
  - bin/license-check-darwin.sha256
  - bin/license-check.exe
  - bin/license-check.exe.sha256
  - bin/license-check-arm64
  - bin/license-check-arm64.sha256
  - bin/license-check-armhf
  - bin/license-check-armhf.sha256
  - bin/license-check-ppc64le
  - bin/license-check-ppc64le.sha256
  - bin/license-check-s390x
  - bin/license-check-s390x.sha256
  skip_cleanup: true
  on:
    tags: true

env: GO111MODULE=off

before_deploy:
- "./ci/hashgen.sh"
